version: '3.6'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: cells_prod_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - prod_static:/code/staticfiles/
      - prod_media:/code/mediafiles/
    expose:
      - 8000
    env_file: backend.env
    networks:
      - production
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    container_name: cells_prod_db
    volumes:
      - prod_postgres:/var/lib/postgresql/data/
    env_file: db.env
    networks:
      - production

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - API_URL=/api
    container_name: cells_prod_web
    volumes:
      - prod_static:/usr/src/cells/staticfiles/
      - prod_media:/usr/src/cells/mediafiles/
    ports:
      - 8888:80
    networks:
      - production
    depends_on:
      - backend

volumes:
  prod_postgres:
  prod_static:
  prod_media:

networks:
  production:
