version: '3'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: cells_api
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/code/staticfiles/
      - media:/code/mediafiles/
    expose:
      - 8000
    env_file: api.env
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    container_name: cells_db
    volumes:
      - data:/var/lib/postgresql/data/
    env_file: db.env
    expose:
      - 5432
    networks:
      - net

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - API_URL=/api
    container_name: cells_web
    volumes:
      - static:/usr/src/cells/staticfiles/
      - media:/usr/src/cells/mediafiles/
    ports:
      - 8888:80
    networks:
      - net
    depends_on:
      - api

volumes:
  data:
  static:
  media:

networks:
  net:
