version: '3.6'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles/
      - media_volume:/code/mediafiles/
    expose:
      - 8000
    env_file: backend.env
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: db.env

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - API_URL=http://localhost:1337/api
    volumes:
      - static_volume:/usr/src/cells/staticfiles/
      - media_volume:/usr/src/cells/mediafiles/
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: