version: '3.6'

services:
  
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=very_secret_key
      - DB_ENGINE=django.db.backends.postgresql
      - DB_DATABASE=cells_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE=postgres
      - SUPERUSER_EMAIL=root@cells.mail
      - SUPERUSER_PASSWORD=superuser
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cells_dev

  db-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=email
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8888:80

  frontend:
    build: ./frontend
    command: npm run serve -- --port 8080
    volumes:
      - ./frontend/:/code/
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  postgres_data_dev: