# Generated by Django 2.2 on 2019-08-31 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresMap',
            fields=[
                ('cols', models.PositiveSmallIntegerField()),
                ('rows', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_str', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares_maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
